<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_16</name>
   <tag></tag>
   <elementGuidId>74c8e972-fa93-4c77-942f-dfb5d644368e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mkUa.mkUa-pres-mcfly.mkUa-isEndDate.mkUa-isSelected.mkUa-isFocused.mkUa-isHighlighted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='GdfA']/div[13]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div[19]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ada51614-34ef-4e7a-8e7a-c42a08380d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkUa mkUa-pres-mcfly mkUa-isEndDate mkUa-isSelected mkUa-isFocused mkUa-isHighlighted</value>
      <webElementGuid>f29473d0-36aa-4d24-bbbe-68eb1a27ae5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>60de5583-72fe-4d45-bde7-853cdb336193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c26caf8e-25ae-48bc-b4db-23181256a6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>478ab2bd-35f0-413d-806d-463623a6224a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>16 de septiembre de 2022</value>
      <webElementGuid>3cc9a35b-ee06-4f9c-bbe1-54b858fa0271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>7832f4d6-d81e-4218-8a14-a45d528e0261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GdfA&quot;)/div[@class=&quot;ui-dialog-Popover c2wZD-popover c2wZD-pres-default mod-layer-default&quot;]/div[@class=&quot;c2wZD-wrapper&quot;]/div[@class=&quot;c2wZD-content&quot;]/div[@class=&quot;KK6S-dropdownContentWrapper KK6S-flexModeTabs&quot;]/div[@class=&quot;KK6S-calendarWrapper&quot;]/div[@class=&quot;ATGJ ATGJ-pres-mcfly ATGJ-double&quot;]/div[@class=&quot;ATGJ-monthWrapper&quot;]/div[@class=&quot;onx_ onx_-pres-mcfly onx_-double&quot;]/div[@class=&quot;onx_-days&quot;]/div[@class=&quot;mkUa mkUa-pres-mcfly mkUa-isEndDate mkUa-isSelected mkUa-isFocused mkUa-isHighlighted&quot;]</value>
      <webElementGuid>f6f30b6c-142f-43ea-acbd-7f3db70fbdb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='GdfA']/div[13]/div/div[2]/div/div[2]/div/div[2]/div/div[2]/div[19]</value>
      <webElementGuid>0b3326fe-898a-4487-9e16-d0db6ecc7bf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D'])[1]/following::div[20]</value>
      <webElementGuid>49351f06-d18f-4c4e-9407-b9e9d88d8ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/following::div[21]</value>
      <webElementGuid>ed2c75df-1d0b-4ade-8333-2eac7c179376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='octubre 2022'])[1]/preceding::div[17]</value>
      <webElementGuid>691c6293-14bb-4b90-9ff7-447f42d130b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='L'])[2]/preceding::div[18]</value>
      <webElementGuid>b4a3b01e-bcb6-4350-8658-1453d40f1b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='16']/parent::*</value>
      <webElementGuid>725971b8-ea47-43ef-a09d-f6e3e3bf4f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[19]</value>
      <webElementGuid>dfd6b187-7683-40d5-b035-02be664d92f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '16' or . = '16')]</value>
      <webElementGuid>a8861f4c-6093-4b6d-8721-0fe508a05a67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
