<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_4</name>
   <tag></tag>
   <elementGuidId>7c1e9254-3f07-4966-8805-c0887f99d4fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.mkUa.mkUa-pres-mcfly.mkUa-isFocused.mkUa-isHighlighted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='GdfA']/div[13]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/div[9]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e586324e-a4b6-4e96-9213-7660349bea4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mkUa mkUa-pres-mcfly mkUa-isFocused mkUa-isHighlighted</value>
      <webElementGuid>7a8dc1c6-b8e7-492b-9451-c7a205061779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>066e4640-2eac-4728-8b5b-6e2298a59700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2529ef7c-0390-4384-8e1e-fb96bab2531c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4781b659-dd6c-4c5e-81cb-91b59b102b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>4 de octubre de 2022</value>
      <webElementGuid>050e850a-f4e6-4fc3-b0aa-9412f639ae6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>42494ae6-d262-4518-a283-0eca93abf066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GdfA&quot;)/div[@class=&quot;ui-dialog-Popover c2wZD-popover c2wZD-pres-default mod-layer-default&quot;]/div[@class=&quot;c2wZD-wrapper&quot;]/div[@class=&quot;c2wZD-content&quot;]/div[@class=&quot;KK6S-dropdownContentWrapper KK6S-flexModeTabs&quot;]/div[@class=&quot;KK6S-calendarWrapper&quot;]/div[@class=&quot;ATGJ ATGJ-pres-mcfly ATGJ-double&quot;]/div[@class=&quot;ATGJ-monthWrapper&quot;]/div[@class=&quot;onx_ onx_-pres-mcfly onx_-double&quot;]/div[@class=&quot;onx_-days&quot;]/div[@class=&quot;mkUa mkUa-pres-mcfly mkUa-isFocused mkUa-isHighlighted&quot;]</value>
      <webElementGuid>d1deff33-515f-4a8f-9e5e-97c86dc1e320</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='GdfA']/div[13]/div/div[2]/div/div[2]/div/div[2]/div[2]/div[2]/div[9]</value>
      <webElementGuid>9b395a93-06d9-4ec7-8b60-340b27d1655a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='D'])[2]/following::div[10]</value>
      <webElementGuid>c047dd77-3e3e-46a4-a25f-d020e9dc985c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::div[11]</value>
      <webElementGuid>539d912d-0f32-4bb8-b20a-f2e3d426a42d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 598 +'])[1]/preceding::div[38]</value>
      <webElementGuid>b0ebf41f-6833-4437-8613-29cbfa33cbe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 793 +'])[1]/preceding::div[39]</value>
      <webElementGuid>df44c501-39f5-4479-b238-71ef487eef9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[9]</value>
      <webElementGuid>cb228641-311d-48ec-8633-996682d67c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '4' or . = '4')]</value>
      <webElementGuid>6bc4741b-6c65-4905-8d85-b6fe97314b5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
