<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Lima (LIM)_k_my-input</name>
   <tag></tag>
   <elementGuidId>7687ec03-d511-4f6a-867c-526d52f229d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.k_my.k_my-mod-theme-mcfly-search.k_my-mod-radius-base.k_my-mod-size-large.k_my-mod-font-size-base.k_my-mod-spacing-default.k_my-mod-text-overflow-ellipsis.k_my-mod-state-focus > input.k_my-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value=''])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fda40b93-87ff-468c-ae5a-170b31f6e028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4ce445e-af15-4f3c-8f3f-5b9b3ca014f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>k_my-input</value>
      <webElementGuid>79bc50c9-e2db-47f5-85c1-56daa8820772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4fe17c3c-2858-4496-b483-16de0b257368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6eb2883b-6f39-4fd4-ad03-db91dd99555e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Destino</value>
      <webElementGuid>de6ff802-9c76-4146-8dab-9725e6a10bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Destino</value>
      <webElementGuid>74a734be-daaa-4998-99db-c9f9cf30866f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UJVc&quot;)/div[@class=&quot;kml-layout mod-full&quot;]/div[@class=&quot;zEiP zEiP-pres-default zEiP-mod-with-drawer&quot;]/div[@class=&quot;kml-layout zEiP-formAndCmp2Container&quot;]/div[@class=&quot;zEiP-formContainer&quot;]/div[@class=&quot;zEiP-formBody&quot;]/div[@class=&quot;zEiP-formFieldOutline&quot;]/div[@class=&quot;zEiP-formField zEiP-destination&quot;]/div[@class=&quot;BCcW&quot;]/div[@class=&quot;k_my k_my-mod-theme-mcfly-search k_my-mod-radius-base k_my-mod-size-large k_my-mod-font-size-base k_my-mod-spacing-default k_my-mod-text-overflow-ellipsis k_my-mod-state-focus&quot;]/input[@class=&quot;k_my-input&quot;]</value>
      <webElementGuid>7281876d-2bd9-4c10-9e82-2354bb528d48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value=''])[2]</value>
      <webElementGuid>55ce4a1e-6f35-48d6-ba77-378e7711cc06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UJVc']/div/div/div/div/div[2]/div/div[3]/div/div/input</value>
      <webElementGuid>f6c4970f-05c3-4f94-954d-004c2a0c051b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>1bbb66de-6fb1-4bc3-91f6-306c94705e9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Destino']</value>
      <webElementGuid>712014f4-7217-497d-af83-811ec9c4711e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
